from tkinter import *
con = Tk ()
con.title("CONCATINATION")
con.geometry("500x200+0+100")
def concat ():
    a=str(labelname.get())
    b=str(labelname1.get())
    c=a+" "+b
    output.config(text=c)
labeltitle=Label(con,text="Concatination")
labeltitle.grid(row=1,column=80,padx=40,pady=40)
labelname=Label(con,text="Enter Your First Name")
labelname.grid(row=2,column=30,padx=40,pady=40)
labelname=Entry(con,width=50)
labelname.grid(row=2,column=40)
labelname1=Label(con,text="Enter your Last Name")
labelname1.grid(row=3,column=30)
labelname1=Entry(con,width=50)
labelname1.grid(row=3,column=40)
output=Label(con,text="OUTPUT")
output.grid(row=4,column=30,padx=40,pady=40)
output=Entry(con,width=50)
output.grid(row=4,column=40)
but=Button(con,text="OK",command=concat)
but.grid(row=6,column=60,padx=40,pady=40)
con.mainloop ()