import tkinter as tk
win=tk.Tk()
win.geometry("500x500")
win.title("Untilted - Notepad")
def quit ():
    win.destroy ()
def AboutNotepad ():
    abt=tk.Tk ()
    abt.title ("About As")
    abt.geometry("300x300")
    message="""Welcome to Notepad
    Created on :22-02-2024
    by Lavanya"""
    lntinfo=tk.Label(abt,text=message)
    lntinfo.pack() 
    abt.mainloop ()
menubar=tk.Menu(win)
filemenu=tk.Menu(menubar,tearoff=0)
menubar.add_cascade(label="File",menu=filemenu,underline=0)
filemenu.add_command(label="New",underline=0,accelerator="Ctrl+N")
filemenu.add_command(label="New Window",underline=4,accelerator="Ctrl+Shift+N")
filemenu.add_command(label="Open",underline=0,accelerator="Ctrl+O")
filemenu.add_command(label="Save",underline=0,accelerator="Ctrl+S")
filemenu.add_command(label="Save As",underline=0,accelerator="Ctrl+Shift+S")
filemenu.add_separator()
filemenu.add_command(label="PageSetup",underline=7,accelerator="Alt+F")
filemenu.add_command(label="Print",underline=0,accelerator="Ctrl+P")
filemenu.add_separator()
filemenu.add_command(label="Exit",underline=1,accelerator="Alt+F")
editmenu=tk.Menu(menubar,tearoff=0)
menubar.add_cascade(label="Edit",menu=editmenu)
editmenu.add_command(label="Undo",underline=0,accelerator="Ctrl+Z")
editmenu.add_command(label="Redo",underline=4,accelerator="Ctrl+y")
editmenu.add_separator ()
editmenu.add_command(label="Copy",underline=0,accelerator="Ctrl+c")
editmenu.add_command(label="Cut",underline=0,accelerator="Ctrl+x")
editmenu.add_command(label="Paste",underline=0,accelerator="Ctrl+v")
formatmenu=tk.Menu(menubar,tearoff=0)
menubar.add_cascade(label="Format",menu=formatmenu,underline=1)
formatmenu.add_command(label="Word Wrap",underline=0)
formatmenu.add_command(label="Font...",underline=0)
viewmenu=tk.Menu(menubar,tearoff=0)
menubar.add_cascade(label="View",menu=viewmenu,underline=0)
viewmenu.add_command(label="Zoom",underline=0)
viewmenu.add_command(label="Status Bar",underline=0)
helpmenu=tk.Menu(menubar,tearoff=0)
menubar.add_cascade(label="Help",menu=helpmenu,underline=0)
helpmenu.add_command(label="View Help",underline=0)
helpmenu.add_command(label="Send Feedback",underline=0)
helpmenu.add_command(label="About Notepad",underline=0,command=AboutNotepad)
win.config(menu=menubar)
win.mainloop ()

