from tkinter import *
from tkinter import ttk
from db import *
import mysql.connector 
win=Tk ()
win.title("Student Mark List")
win.geometry("500x500")
mydbcon=DBManipulate ()
def exitParent ():
    win.destroy ()
def inserttoDB ():
    nameety=Name1.get ()
    tamilety=Tamil1.get ()
    englishety=English1.get ()
    mathsety=Maths1.get ()
    scienceety=Science1.get ()
    socialety=Social.get ()
    x=mydbcon.insertvalues(nameety,tamilety,englishety,mathsety,scienceety,socialety)
    lblconMsg.config(text=x)
tablist=ttk.Notebook(win)
tablist.pack(padx=10,pady=5)
tabInsert=ttk.Frame(tablist,width=win.winfo_screenwidth (),height=win.winfo_screenheight ())
tabInsert.pack()
tabUpdate=ttk.Frame(tablist,width=win.winfo_screenwidth (),height=win.winfo_screenheight ())
tabUpdate.pack ()
tabDelete=ttk.Frame(tablist,width=win.winfo_screenwidth (),height=win.winfo_screenheight ())
tabDelete.pack ()
tablist.add(tabInsert,text="Insert")
tablist.add(tabUpdate,text="Update")
tablist.add(tabDelete,text="Delete")
titledisplayframeintab=Frame(tabInsert,width=win.winfo_screenwidth(),height=win.winfo_screenheight())
titledisplayframeintab.pack()
lbltitle=Label(titledisplayframeintab,text="Inserting Student Table",font="40")
lbltitle.grid(row=0,columnspan=10,padx=10)
Name=Label(titledisplayframeintab,text="Name")
Name.grid(row=2,columnspan=1,padx=10,pady=10)
Name1=Entry(titledisplayframeintab,width=30)
Name1.grid(row=2,column=10,padx=10,pady=10)
Tamil=Label(titledisplayframeintab,text="Tamil")
Tamil.grid(row=3,columnspan=1,padx=10,pady=10)
Tamil1=Entry(titledisplayframeintab,width=30)
Tamil1.grid(row=3,column=10,padx=10,pady=10)
English=Label(titledisplayframeintab,text="English")
English.grid(row=4,columnspan=1,padx=10,pady=10)
English1=Entry(titledisplayframeintab,width=30)
English1.grid(row=4,column=10,padx=10,pady=10)
Maths=Label(titledisplayframeintab,text="Maths")
Maths.grid(row=5,columnspan=1,padx=10,pady=10)
Maths1=Entry(titledisplayframeintab,width=30)
Maths1.grid(row=5,column=10,padx=10,pady=10)
Science=Label(titledisplayframeintab,text="Science")
Science.grid(row=6,columnspan=1,padx=10,pady=10)
Science1=Entry(titledisplayframeintab,width=30)
Science1.grid(row=6,column=10,padx=10,pady=10)
Social=Label(titledisplayframeintab,text="Social")
Social.grid(row=7,columnspan=1,padx=10,pady=10)
Social1=Entry(titledisplayframeintab,width=30)
Social1.grid(row=7,column=10,padx=10,pady=10)
btn=Button(titledisplayframeintab,text="OK")
btn.grid(row=8,column=2,padx=10,pady=10)
btn1=Button(titledisplayframeintab,text="Cancel")
btn1.grid(row=8,column=5,padx=10,pady=10)
btn2=Button(titledisplayframeintab,text="Submit")
btn2.grid(row=8,column=7,padx=10,pady=10)
lblconMsg=Label(titledisplayframeintab,text='')
lblconMsg.grid(row=9,column=8,pady=20)
resultframe=Frame(titledisplayframeintab,width=800,height=700,bg="Black")
resultframe.grid(row=10,columnspan=9)
win.mainloop ()