from tkinter import *
import mysql.connector
win=Tk ()
win.title("Insert into MySQL DB Demo")
win.geometry("500x500")
class frameDBOperation:
    def __init__(self):
        frametop=Frame(win,bg="black",width=500,height=500,padx=30,pady=30)
        frametop.pack(side=TOP)
        btinsert=Button(frametop,text="INSERT",command=self.frameleft).pack(padx=10,pady=10)
        btupdate=Button(frametop,text="UPDATE",command=self.rightframe).pack(padx=10,pady=10)
        btdelete=Button(frametop,text="DELETE",command=self.bottomframe).pack(padx=10,pady=10)
    def frameleft(self):
        frameleft=Frame(win,bg="black",width=500,height=500,padx=30,pady=30)
        frameleft.pack(side=LEFT)
        lbl_Title_of_Operation=Label(frameleft,text="Insert into MySQL DB Demo")
        lbl_Title_of_Operation.grid(row=0,columnspan=5)
        lblname=Label(frameleft,text="Name")
        lblname.grid(row=2,column=0,padx=30,pady=10)
        lblentry=Entry(frameleft,width=30)
        lblentry.grid(row=2,column=1,padx=30,pady=10)
        lblTamil=Label(frameleft,text="Tamil")
        lblTamil.grid(row=3,column=0,padx=30,pady=10)
        lblentry1=Entry(frameleft,width=30)
        lblentry1.grid(row=3,column=1,padx=30,pady=10)
    def rightframe(self):
        frameright=Frame(win,bg="Red",width=500,height=500,padx=30,pady=30)
        frameright.pack(side=RIGHT)
        lbltitleofoperation1=Label(frameright,text="Update into MySQL DB Demo")
        lbltitleofoperation1.grid(row=0,columnspan=5)
        lblname1=Label(frameright,text="Name")
        lblname1.grid(row=2,column=0,padx=30,pady=30)
        rightentry=Entry(frameright,width=30)
        rightentry.grid(row=2,column=1,padx=30,pady=10)
        lbltamil1=Label(frameright,text="Tamil")
        lbltamil1.grid(row=3,column=0,padx=30,pady=10)
        rightentry1=Entry(frameright,width=30)
        rightentry1.grid(row=3,column=1,padx=30,pady=10)
    def bottomframe (self):
        framebottom=Frame(win,bg="skyblue",width=500,height=500,padx=30,pady=30)
        framebottom.pack(side=BOTTOM)
        lbltitleofoperation2=Label(framebottom,text="Delete into MySQL DB Demo")
        lbltitleofoperation2.grid(row=0,columnspan=5)
        lblname2=Label(framebottom,text="Name")
        lblname2.grid(row=2,column=0,padx=30,pady=10)
        bottomentry=Entry(framebottom,width=30)
        bottomentry.grid(row=2,column=1,padx=30,pady=10)
        lbltamil2=Label(framebottom,text="Tamil")
        lbltamil2.grid(row=3,column=0,padx=30,pady=30)
        bottomentry1=Entry(framebottom,width=30)
        bottomentry1.grid(row=3,column=1,padx=30,pady=10)
run=frameDBOperation ()
win.mainloop ()
